### ISSUE TITLE
[Feature] Linux build

### ISSUE THREAD

**Issue by Clearmist** [satisfactorymodding/SatisfactoryModLoader#114]
With the release of dedicated servers: SML running on Linux would allow dedicated servers to run mods. The plugin is detected by the game server, but fails to load because the plugin was built for Windows.

**Comment by Vilsol** [comment]
This is planned, but until recently our top priority was to get SML and the rest of modding workflow working on the latest U5. Before we can even continue with this, we also are blocked by our engine which needs to also be compiled for Windows and Linux server targets.

**Comment by Clearmist** [comment]
I sympathize :) I tried compiling SML from source on Linux last night for a few hours and it was a headache that eventually went nowhere. Thank you for using your expertise for the benefit of others.

**Comment by farvour** [comment]
Nice. Looking forward to a Linux build for the dedicated servers. Also, it probably goes without saying, but the entire SMM+SML suite should have a headless mode for people who are using Linux dedicated. Generally we don't install or use X interfaces, especially when building immutable containers of the game server for use with Docker ;)

**Comment by farvour** [comment]
> I sympathize :) I tried compiling SML from source on Linux last night for a few hours and it was a headache that eventually went nowhere. Thank you for using your expertise for the benefit of others.

I haven't tried yet, but I would suspect there are a ton of places where it's very possible this won't even work with the current Engine due to the game released with the Unreal engine itself not having a Linux native build or libraries available to utilize for linking. The modding community may even have to wait for the upstream developers at CS to provide this outside the scope of the dedicated server. But I do not know. I had a look at the GitHub actions workflow and there's a lot of reliance on .NET on Windows commands (msbuild for example) and you can't even get access to those on Linux without .NET 5.0+ I believe.

**Comment by Vilsol** [comment]
There is a CLI version of SMM currently in development, it will have both an interactive and non-interactive mode.

As regarding to building for Linux, UE4 supports cross-compilation from Windows to Linux (sadly not the other way around), so we will still be utilizing all of our existing workflows and toolchains, just need to make some adjustments to be OS-generic.

Here are the docs on that: https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/Linux/GettingStarted/

**Comment by farvour** [comment]
> There is a CLI version of SMM currently in development, it will have both an interactive and non-interactive mode.
> 
> As regarding to building for Linux, UE4 supports cross-compilation from Windows to Linux (sadly not the other way around), so we will still be utilizing all of our existing workflows and toolchains, just need to make some adjustments to be OS-generic.
> 
> Here are the docs on that: https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/Linux/GettingStarted/

Excellent. I like the CLI approach! 👍 

As far as cross-compiling, I remember this. It's similar to Unity as well. You can build on Windows (for Linux) but not Linux for Linux :/ I guess that just means from a containerization perspective, some other build job that has access to a Windows build environment would have to build the plugin first, before the .so file can be copied into the container for consumption by the Linux build of the game. I'm only making a wild guess that is going to be the case for that. As a user/consumer this probably won't matter to 99% of users since they will be downloading the shared module that is already built for the game. As a person with SW development experience, knowing this is still important for potentially contributing to the development process. :)

**Comment by thraidh** [comment]
You can definitely compile and run all of UE4 including editor on Linux and produce output for Linux. I don't know if you can cross-compile on Linux for Windows. I also never tried to make a shipping build, so if that is what you are talking about, it may not work.

**Comment by tesla-srt** [comment]
So what is the next steps for getting dedicated servers with mods on linux boxes?
Is there anything that I can help with?

**Comment by kkoshelev** [comment]
I can see that all the releases only have Win64 binaries. How do I get binaries for Linux?

**Comment by zpangwin** [comment]
> How do I get binaries for Linux?

My understanding is they don't exist yet... from above it sounds like the Linux side of things is planned but still not solved for currently. For client-side, SML works fine. For dedicated servers, in theory you could try installing the windows version of the server with something like `steamcmd +@sSteamCmdForcePlatformType windows +login anonymous +force_install_dir "/wine-servers/satisfactory" +app_update 1690800 -beta public validate +quit` (similar to what folks do for running Conan Exiles dedi under wine) and using the Win64 binaries of SM. I don't think it would work (yet)... I haven't tested it.

If any who are more involved knows otherwise, please feel free to correct me / add more depth.

**Comment by Joly0** [comment]
Are there any news on this one?

**Comment by sanegaming** [comment]
I am running satisfactory from Pterodactyl panel, would love to see an update to this to support mods.

**Comment by budak7273** [comment]
[Vilsol's earlier message](https://github.com/satisfactorymodding/SatisfactoryModLoader/issues/114#issuecomment-979480841) still summarizes the current situation. Keep an eye on the dedicated servers branch for progress on this.

**Comment by Joly0** [comment]
Hey guys, its been a while and there hasnt been much progress on the dedicated servers branch, so any update on whats the current status :)

**Comment by budak7273** [comment]
@Joly0 Update 8 support (SML 3.6.0) takes priority
