### ISSUE TITLE
no access???

### ISSUE THREAD

**Issue by mjsjnr** [satisfactorymodding/SatisfactoryModLoader#133]
running windows 11...  i start the app(satisfactory mod loader) it appears in my taskbar at bottom, but not on main window....if i alt and tab, its visable ... but i cant click on it???so i know its running, but cant click are access it to alter any mods??? what have i done???

**Comment by budak7273** [comment]
This report should be on [SatisfactoryModManager](https://github.com/satisfactorymodding/SatisfactoryModManager).

The issue is that the window somehow got offscreen. To fix it you need to go in `%appdata%\SatisfactoryModManager\settings.json` and in `windowLocation` set the x and y to 0 to bring the window back on the screen. Restart SMM after you do that.
