### ISSUE TITLE
File Location Issue

### ISSUE THREAD

**Issue by Aidenboss434** [satisfactorymodding/SatisfactoryModLoader#328]
I installed Satisfactory in a location that is not the default file location and i cant find out how to change it in SMM.

Here's The Error

![Image](https://github.com/user-attachments/assets/00deb813-1320-4dfb-8ee2-69fa5d546778)

**Comment by MinoDab492** [comment]
1. You'd be better off asking for help in the Discord, since it'll be seen more likely (https://discord.ficsit.app)
2. How did you move it's install? If you manually copy the files, the manager can't find it. If you moved it using the built-in tool in Steam, or if you installed it somewhere else by changing the install path when installing in Epic Games, or to another library path on Steam, then it should work.
3. How do you own the game? Epic Games, Steam, or cracked?

**Comment by Aidenboss434** [comment]
I used [https://steamunlocked.net/](url) to download Satisfactory

**Comment by Borketh** [comment]
We do not support pirated copies of the game.
